#!/bin/bash

function expected_nchunk() {
    local GENOTYPEFILE=$1
    local NMAX=$2
    NSNPS=$( zcat ${GENOTYPEFILE} | wc -l )
    NSNPS=$( echo $(( NSNPS - 1 )) ) # only one line of header
    NCHUNK=$( echo $(( (NSNPS + NMAX - 1)/NMAX )) )
    echo $NCHUNK
}

function tejaas_chunk_reduce() {

    local DIR=$1
    local NCHUNK=$2
    local CWD=$( pwd )
    cd $DIR
    for EXT in rr.txt gene_snp_list.txt gene_snp_list_knn.txt; do

        # start the process only if chunk000 has been created
        if [ -f chunk000_${EXT} ]; then

            # check write access in the target folder / also copy the header line
            head -n 1 chunk000_${EXT} > ${EXT}
            if [ -f ${EXT} ]; then

                # loop over all chunks and count the number of SNPs for which the statistic has been calculated
                NCALCSNPS=1
                COLLECT=true
                for (( i=0; i<${NCHUNK}; i++ )); do
                    NUM=$( echo $i | awk '{printf "%03d\n", $1}' )
                    FILENAME="chunk${NUM}_${EXT}"
                    # If the chunk exists, concatenate.
                    if [ -f ${FILENAME} ]; then
                        tail -n +2 ${FILENAME} >> ${EXT}
                        N=$( wc -l ${FILENAME} | awk '{print $1}' )
                        NCALCSNPS=$((NCALCSNPS + N - 1))
                    else
                        echo "${DIR} --> ${EXT} --> Could not find chunk${NUM}."
                        COLLECT=false
                    fi
                done
    
                # after all files have been collected (COLLECT=true), check if the line numbers match
                # if the line numbers don't match, then there is some unknown error.
                # Investigate.
                if [ "${COLLECT}" = "true" ]; then
                    NLINES_EXT=$( wc -l ${EXT} | awk '{print $1}' )
                    if [ "${NLINES_EXT}" -eq "${NCALCSNPS}" ]; then
                        echo "${DIR} --> ${EXT} --> Done."
                        # Now you can remove the chunks
                        # If some chunk has failed while running, it will have less SNPs than it should have
                        rm -rf chunk*_${EXT} 
                    else
                        echo "${DIR} --> ${EXT} --> Line numbers do not match."
                    fi
                fi
           else
                echo "${DIR} --> ${EXT} --> Could not create target file, check write access." 
           fi
        else
            echo "${DIR} --> ${EXT} --> Could not find the first chunk."
        fi

    done
    cd $CWD
}
