#!/bin/bash

THISMETHOD="jpa"
GENEINFOFILE=${SIMGXFILE/\.txt/\.gtf\.gz}
EXTRAFLAGS="--trim"
if [ "${SHUFFLE}" = "true" ]; then
    THISMETHOD="jpa_rand"
    SHUFFLED_ID_FILE=${SIMGTFILE/\.vcf\.gz/\.shuf}
    EXTRAFLAGS="$EXTRAFLAGS --shuffle-with $SHUFFLED_ID_FILE"
fi

for PRIDX in ${!JPA_PREPROC[*]}; do ## a funky construct to get the indices of the array

    PRCC=${JPA_PREPROC[PRIDX]}
    KNN_NBR=${JPA_KNN[PRIDX]}

    __DIR=$( dirname ${GXPROCFILE} )
    __FIL=$( basename ${GXPROCFILE} )
    __PRF="${__FIL%%.*}_${PRCC}"
    if [ ! "${NPEER}" = "0" ]; then
        __PRF="${__PRF}_${NPEER}_PEER_residuals"
    fi
    INPUTGXFILE="${__DIR}/${__PRF}_norm.txt"
    __EFLAGS="${EXTRAFLAGS} --knn ${KNN_NBR}" ## because we don't want inplace modification of $EXTRAFLAGS within the loop


    PRCCMOD=${PRCC}
    if [ ! "${KNN_NBR}" = "0" ]; then
        PRCCMOD="${PRCCMOD}_knn${KNN_NBR}"
    fi
    SPECIFIC_JOBSUBDIR="${JOBSUBDIR_SIM}/${THISMETHOD}/${PRCCMOD}/peer${NPEER}"
    SPECIFIC_OUTDIR="${OUTDIR_SIM}/${THISMETHOD}/${PRCCMOD}/peer${NPEER}"
    NULLSCORE_FILE="${SPECIFIC_OUTDIR}/null_scores.txt"
    JPA_JOBNAME="${THISMETHOD}_sim${SIMINDEX}_${PRCCMOD}_peer${NPEER}_${PARAMSTR}_${RANDSTRING}"

    if [ -d ${SPECIFIC_JOBSUBDIR} ]; then rm -rf ${SPECIFIC_JOBSUBDIR}; fi; mkdir -p ${SPECIFIC_JOBSUBDIR}
    if [ ! -d ${SPECIFIC_OUTDIR} ];  then mkdir -p ${SPECIFIC_OUTDIR}; fi
    sed "s|_JOB_NAME|${JPA_JOBNAME}|g;
         s|_PYT_ENV_|${PYTHON36}|g;
         s|_TEJ_PYT_|${TEJAASPY}|g;
         s|_GT_FILE_|${SIMGTFILE}|g;
         s|_EXPR_FL_|${INPUTGXFILE}|g;
         s|_GEN_POSF|${GENEINFOFILE}|g;
         s|_OUT_PRFX|${SPECIFIC_OUTDIR}/all|g;
         s|_NUL_FIL_|${NULLSCORE_FILE}|g;
         s|_CIS_WIN_|0|g;
         s|_EXT_FLAG|\"${__EFLAGS}\"|g;
        " ${MASTER_BSUBDIR}/jpa.bsub > ${SPECIFIC_JOBSUBDIR}/${JPA_JOBNAME}.sbatch
    JPA_JOBID=$( submit_job ${SPECIFIC_JOBSUBDIR} ${JPA_JOBNAME} ${PREPROC_JOBDEPS} )
    JPA_JOBDEPS=$( add_deps "${JPA_JOBDEPS}" ${JPA_JOBID} )

    __STDSTR="    ${JPA_JOBID} > JPA on ${PRCCMOD} + ${NPEER} peer"
    if [ "${SHUFFLE}" = "true" ]; then
        __STDSTR="${__STDSTR} + shuffled genotype"
    fi

    echo "${__STDSTR}. ${PREPROC_JOBDEPS}"

done
