#!/bin/bash

function submit_job_echo() {
    local DIR=$1
    local JOBNAME=$2
    local DEPS=$3
    local CWD=`pwd`
    cd ${DIR}
    echo ${JOBNAME}.bsub
    cd ${CWD}
}

function submit_job() {

    local DIR=$1
    local JOBNAME=$2
    local DEPS=$3
    local CWD=$( pwd )
    cd ${DIR}

    SUCCESS=false

    while [ "${SUCCESS}" = "false" ]; do
        if [ ! "${DEPS}" = "None" ]; then
            STDOUTPUT=$( sbatch --dependency=${DEPS} ${JOBNAME}.sbatch )
        else
            STDOUTPUT=$( sbatch ${JOBNAME}.sbatch )
        fi
        if [ "${STDOUTPUT%% *}" = "Submitted" ]; then 
            SUCCESS=true
            sleep 1 # pause to be kind to the scheduler
        else
            sleep 10 # pause more to get the system back to working
        fi
    done

    JOBID="${STDOUTPUT##* }"
    cd ${CWD}
    echo ${JOBID}
}

function submit_job_array() {

    local DIR=$1
    local JOBNAME=$2
    local DEPS=$3
    local NARR=$4
    local CWD=`pwd`

    cd ${DIR}

    SUCCESS=false

    while [ "${SUCCESS}" = "false" ]; do
        if [ ! "${DEPS}" = "None" ]; then
            STDOUTPUT=$( sbatch --dependency=${DEPS} --array=0-${NARR} ${JOBNAME}.sbatch )
        else
            #STDOUTPUT=$( sbatch --array=0-${NARR}%20 ${JOBNAME}.slurm )
            STDOUTPUT=$( sbatch --array=0-${NARR} ${JOBNAME}.sbatch )
        fi

        if [ "${STDOUTPUT%% *}" = "Submitted" ]; then
            SUCCESS=true
            sleep 1 # pause to be kind to the scheduler
        else
            sleep 10 # pause more to get the system back to working
        fi
    done

    JOBID="${STDOUTPUT##* }"

    cd ${CWD}
    echo ${JOBID}
}

function submit_job_lsf() {

    local DIR=$1
    local JOBNAME=$2
    local DEPS=$3
    local CWD=`pwd`

    cd ${DIR}

    if [ ! "${DEPS}" = "None" ]; then
        echo "Submitting job with dependency ${DEPS}"
        STDOUTPUT=$( bsub -w "${DEPS}" < ${JOBNAME}.bsub )
    else
        STDOUTPUT=$( bsub < ${JOBNAME}.bsub )
    fi

    JOBID="${STDOUTPUT##* }"
    
    cd ${CWD}
    echo $JOBID
}

    # ok=0
    # # workaround, sometimes the file was submitted to the cluster but not written to disk yet
    # while [ $ok -lt 1 ]; do
    #     if [ -s ${JOBNAME}.bsub ]; then
    #         bsub < ${JOBNAME}.bsub
    #         ok=1
    #     else
    #         echo "File is empty, retrying.."
    #         sleep 1;
    #     fi
    # done
