#!/bin/bash

function tejaas_chunk_reduce() {
    local DIR=$1
    local CWD=`pwd`
    cd $DIR
    for EXT in rr.txt gene_snp_list.txt; do # jpa.txt
        if [ -f chunk000_${EXT} ]; then
            NCHUNK=`wc -l chunk*_${EXT} | wc -l | awk '{print $1-1}'`
            NLINES=0
            ERROR=false
            head -n 1 chunk000_${EXT} > ${EXT}

            for ((i=0; i<$NCHUNK; i++)); do
                NUM=`echo $i | awk '{printf "%03d\n", $1}'`
                FILENAME="chunk${NUM}_${EXT}"
                if [ -f ${FILENAME} ]; then
                    tail -n +2 ${FILENAME} >> ${EXT}
                    N=`wc -l ${FILENAME} | awk '{print $1}'`
                else
                    echo "Error in ${DIR}: ${FILENAME} does not exist."
                    ERROR=true
                fi
                NLINES=$((NLINES + N - 1))
            done
            if [ "${ERROR}" = "false" ]; then
                if [ -f ${EXT} ]; then
                    NLINES=$((NLINES + 1))
                    N=`wc -l ${EXT} | awk '{print $1}'`
                    if [ "$N" -eq "$NLINES" ]; then
                        #rm -rf chunk*_${EXT}
                        #echo "Succesfully reduced chunks for $EXT in $DIR"
                        echo "Done. $DIR --> $EXT"
                    else
                        echo "Error in copying chunks for $EXT in $DIR"
                    fi
                else
                    echo "Could not create $EXT in $DIR"
                fi
            else
                echo "Job error for $EXT in $DIR"
            fi
        else
            echo "chunk000_${EXT} does not exist in $DIR"
        fi
    done
    cd $CWD
}
