#!/bin/bash

THISMETHOD="tejaas"
THISJOBDEPS=${PREPROC_JOBDEPS}

# include submission helper
source ${UTILSDIR}/submit_tejaas

EXTRAFLAGS="--trim"
if [ "${SHUFFLE}" = "true" ]; then
    THISMETHOD="tejaas_rand"
    SHUFFLED_ID_FILE=${SIMGTFILE/\.vcf\.gz/\.shuf}
    EXTRAFLAGS="$EXTRAFLAGS --shuffle-with $SHUFFLED_ID_FILE"
fi

MAF_FILE=${SIMGTFILE/\.vcf\.gz/\.altfreq}
GENEINFOFILE=${SIMGXFILE/\.txt/\.gtf\.gz}

for PRIDX in ${!TEJAAS_PREPROC[*]}; do ## a funky construct to get the indices of the array

    PRCC=${TEJAAS_PREPROC[PRIDX]}
    KNN_NBR=${TEJAAS_KNN[PRIDX]}

    __DIR=$( dirname ${GXPROCFILE} )
    __FIL=$( basename ${GXPROCFILE} )
    __PRF="${__FIL%%.*}_${PRCC}"

    if [ ! "${NPEER}" = "0" ]; then
        __PRF="${__PRF}_${NPEER}_PEER_residuals"
    fi
    INPUTGXFILE="${__DIR}/${__PRF}_norm.txt"

    CC_INPUTGXFILE="None"
    if [ "${TEJAAS_TG_PREPROC}" != "None" ]; then
        __TGP="${__FIL%%.*}_${TEJAAS_TG_PREPROC}"
        CC_INPUTGXFILE="${__DIR}/${__TGP}_norm.txt"
    fi

    for NULL in ${TEJAAS_NULL}; do
        if [ ${NULL} == "perm" ]; then __SIGMA_BETA=${TEJAAS_SIGMA_BETA_PERM}; fi
        if [ ${NULL} == "maf" ];  then __SIGMA_BETA=${TEJAAS_SIGMA_BETA_MAF}; fi
        for SBETA in ${__SIGMA_BETA}; do

            __EFLAGS="${EXTRAFLAGS}" ## because we don't want inplace modification of $EXTRAFLAGS within the loop
            METHOD_VARIANT="${NULL}null_sb${SBETA}"

            if [ "${TEJAAS_CISMASK}" = "true" ]; then
                __EFLAGS="${__EFLAGS} --cismask"
            else
                METHOD_VARIANT="${METHOD_VARIANT}_nomask"
            fi

            __EFLAGS="${__EFLAGS} --knn ${KNN_NBR}"
            PRCCMOD=${PRCC}
            if [ ! "${KNN_NBR}" = 0 ]; then
                PRCCMOD="${PRCCMOD}_knn${KNN_NBR}"
            fi

            SPECIFIC_JOBSUBDIR="${JOBSUBDIR_SIM}/${THISMETHOD}/${METHOD_VARIANT}/${PRCCMOD}/peer${NPEER}"
            SPECIFIC_OUTDIR="${OUTDIR_SIM}/${THISMETHOD}/${METHOD_VARIANT}/${PRCCMOD}/peer${NPEER}"
            JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_sim${SIMINDEX}_${PRCCMOD}_peer${NPEER}_${PARAMSTR}_${RANDSTRING}"
            submit_tejaas ${PYTHON36} ${TEJAASPY} ${SIMGTFILE} ${INPUTGXFILE} ${CC_INPUTGXFILE} \
                          ${GENEINFOFILE} ${MAF_FILE} \
                          ${TEJAAS_MODEL} ${NULL} \
                          ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA} \
                          "${__EFLAGS}" \
                          ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                          ${MAX_NSNP_PERJOB} \
                          ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                          TEJAAS_JOBDEPS "${TEJAAS_JOBDEPS}"
            SUBMITTED_JOBIDS=${TEJAAS_JOBDEPS#*${SUBMITTED_JOBIDS}*:}
            __MSTRING="${METHOD_VARIANT} on ${PRCCMOD} + ${NPEER} peer"
            if [ "${SHUFFLE}" = "true" ]; then __MSTRING="${__MSTRING} + shuffled genotype"; fi
            echo "    ${SUBMITTED_JOBIDS} > ${__MSTRING}. ${THISJOBDEPS}"
        done
    done
done
