#!/bin/bash

TEJAASPY="${HOME}/trans-eQTL/codebase/tejaas/main.py"
TEJAASNULL="${HOME}/trans-eQTL/codebase/tejaas/create_jpanull.py"
GNETLMMDIR="${HOME}/packages/GNetLMM"
PLINK19="${HOME}/packages/plink/plink-1.90/plink"
PYTHON27="${HOME}/miniconda3/envs/py27/bin/python"
PYTHON36="${HOME}/miniconda3/envs/py36/bin/python"
