#!/bin/bash
function abs_path() {
    # $1: relative path
    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

# a beautiful one-line to get the full directory name of the location of this script
CURDIRUP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Pipeline directories
UTILSDIR=$(abs_path "${CURDIRUP}/utils")
CONFIGDIR=$(abs_path "${CURDIRUP}/configs")
SCRIPTDIR=$(abs_path "${CURDIRUP}/../scripts")
MASTER_BSUBDIR=$(abs_path "${CURDIRUP}/../bsubfiles")
JOBSUBDIR=$(abs_path "${CURDIRUP}/../jobsubs")
ANALYSISDIR=$(abs_path "${CURDIRUP}/../analysis")

# Script files
MATRIXEQTL_R=$(abs_path "${SCRIPTDIR}/matrixeqtl.R")
SAMPLEGENOPY=$(abs_path "${SCRIPTDIR}/sample_genotype.py")
SIMULATEGXPY=$(abs_path "${SCRIPTDIR}/simulate_expression.py")
ROCSUMMPY=$(abs_path "${ANALYSISDIR}/utils/roc_summarize.py")
