#!/bin/bash

# Simulation parameters
bGenerateData=true
bUseGtexCorr=true
NGENES="15158"
NSAMPLES="450"
NCFS="20"
NCISS="800"
NTFS="30"
NTRANSS="50 100 150"
NOISE_STD_SHAPES="100"
NOISE_STD_SCALES="0.01"
CF_SPARSITYS="0.0"
CF_MEANS="0.0"
CF_STDS="1.0"
CIS_EFFECTS="0.6"
TF_CIS_SHAPES="4.0"
TF_CIS_SCALES="0.1"
TF_TRANS_SHAPES="5 10 15 20"
TF_TRANS_SCALES="0.02"
NPEERCORR="None"

# Simulation controls
STARTSIM=0
NSIM=20

# MatrixEQTL options
bMatrixEqtl=false                        # run the method if true
bMEqtlRandom=false                      # run the method if true
MEQTL_PVALTHRES_CIS=0.001
MEQTL_PVALTHRES_TRANS=0.001
MEQTL_CIS_WINDOW=0
MATRIXEQTL_MODEL="modelLINEAR"

# TEJAAS options
bTejaas=true                            # run the method if true
bTjsRandom=false
TEJAAS_MODEL="jpa-rr"                   # only one model allowed
TEJAAS_NULL="perm"                      # list of null models
TEJAAS_SIGMA_BETA_PERM="0.05"           # list of sigma beta for perm null
TEJAAS_SIGMA_BETA_MAF="0.001"           # list of sigma beta for MAF null
TEJAAS_PRINCIPAL_COMPONENTS="5"
MAX_NSNP_PERJOB=4000                    # number of SNPs for analysis by TEJAAS per job
TEJAAS_SNPS_THRES=0.001                 # all trans-eQTLs are printed, but target genes are printed for those trans-eQTLs below this threshold
TEJAAS_GENE_THRES=0.001                 # even for the above, not all target genes are printed; only those with p-values below this threshold

# JPA options
bTejaasJPA=false
bJPARandom=false

# GNetLMM options
# bGNetLmm=true
# bGNLRandom=true
# GNLMM_SNP_PER_JOB=20000

# Which ROC plots to obtain?
WHICHPLOTS="fpr_tpr nsel_valids thres_tpr tpr_ppv"

# Input and output options
OUTDIRUP="/scratch/sbanerj/trans-eqtl/simulation"
INPUT_GENO_FMT="/scratch/sbanerj/trans-eqtl/input/gtex/genotype/all_samples/GTEx_v6_imput_info04_HWEp1E6_PASS_dbSNP135_maf1_noindels_noambig_chr[CHRM]_WARNimputedmissing.vcf.gz"
GTEX_CORR_FILE="/scratch/sbanerj/trans-eqtl/input/gtex/expression/gtex_correlation.npy"
#GTEX_CORR_FILE="/scratch/sbanerj/trans-eqtl/simulation/gtex_correlation_aa.npy"
#GTEX_CORR_FILE="/scratch/sbanerj/trans-eqtl/simulation/gtex_correlation_lmcorrected_withage_aa_8core.npy"
